[package]
name = "bnf_rules_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
indexmap = "2.0.2"
bnf_rules_parser = { path = "../bnf_rules_parser" }